url: ''
baseurl: ''
compass:
  logo: /images/compass.png
  author: Compass
  tagline: >-
    The <a href='http://jekyllrb.com'>Jekyll</a> theme for your personal landing
    page
  include_content: true
  include_analytics: false
  twitter: compass
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
markdown: kramdown
highlighter: rouge
permalink: pretty
